### ISSUE TITLE
[Q] What do you do when your robot can speed up just fine but it can't slow down fast enough?

### ISSUE THREAD

**Issue by EddieDL** [acmerobotics/road-runner-quickstart#103]
We are using the DriveVelocityPIDTuner OpMode to tune our drive wheel encoders and we are finding that we can update the PID to accurately accelerate and reach max velocity, but when our robot is trying to slow down, we are always behind. None of the documentation really goes into what you would do about that. Is that just something you can ignore?

Also, should the DriveVelocityPIDTunder logic have a short "delay" when the robot is stopped. Just to allow the robot to come to a complete stop before it starts the next motion?

Below is an image of an example run. I know the acceleration phase is not 100% right. This was after we reverted a bunch of our tuning and we slowed down our acceleration by an additional 5%.

![image](https://user-images.githubusercontent.com/10708940/96659471-02f84c80-1315-11eb-8033-bcc19667c589.png)

**Comment by rbrott** [comment]
> Is that just something you can ignore?

This is unfortunately somewhat common. You _can_ ignore it under the assumption that feedback will handle it, although I would keep it in mind as a potential cause of issues down the road. There are a couple strategies to mitigate although none of them are entirely satisfactory.
* Decrease the maximum acceleration even further.
* Increase the velocity gains to close the gap without introducing violent oscillations.

> Also, should the DriveVelocityPIDTunder logic have a short "delay" when the robot is stopped. Just to allow the robot to come to a complete stop before it starts the next motion?

I don't think it's a big deal, but I don't see an issue with adding a delay.
