### ISSUE TITLE
Create a tank LocalizerTest

### ISSUE THREAD

**Issue by NoahBres** [acmerobotics/road-runner-quickstart#112]
The `LocalizerTest` will crash the tank kinematics (cause it to throw [this error](https://github.com/acmerobotics/road-runner/blob/f98e5063d6069dd57a52ff78071b457b83e70a2a/core/src/main/kotlin/com/acmerobotics/roadrunner/kinematics/TankKinematics.kt#L23)) as it generates a holonomic drive signal.

**Comment by rbrott** [comment]
Oops not sure how I missed that in the original review. The `SampleTankDrive#setWeightedDrivePower()` method should just ignore y/strafe and the corresponding weighting coefficient should be removed.
