### ISSUE TITLE
Dashboard disable

### ISSUE THREAD

**Issue by Team14423** [acmerobotics/road-runner-quickstart#135]
Hi -

We have update to the latest version (including .0.4.0 in gradle for Dashboard) but the disable dashboard opmode is not showing up for us. Where do we look for that? Do we need the driver station to be at 6.2 for that? We haven't upgraded that yet.

**Comment by rbrott** [comment]
The latest version has dash 0.4.1. I suspect upgrading will fix the issue.

**Comment by Team14423** [comment]
No luck. We're pulling from Noah's advanced quick start branch. Maybe it's a revision behind, though our code seems to match the instructions on the dashboard install readme.

**Comment by NoahBres** [comment]
That branch used `0.3.10`. It has now been updated to `0.4.1`. Apologies for the inconvenience.

**Comment by Team14423** [comment]
OK, so pull an update and all good?

**Comment by Team14423** [comment]
Thanks all - that worked, all good
