### ISSUE TITLE
Problems install quickstart

### ISSUE THREAD

**Issue by foocross** [acmerobotics/road-runner-quickstart#137]
Downloaded the quickstart and tried to build using Android studio. Got the following error during Gradle sync:

11:16 PM	Gradle sync failed: Could not resolve all dependencies for configuration ':FtcRobotController:debugRuntimeClasspath'.
				Could not determine artifacts for org.tensorflow:tensorflow-lite:1.10.0: Skipped due to earlier error
				Consult IDE log for more details (Help | Show Log) (48 s 364 ms)

We are using Macs

**Comment by rbrott** [comment]
I can't reproduce. Did you get it working?

**Comment by NoahBres** [comment]
Bintray experienced outages on the 15th and 16th. Perhaps this issue was related to that.

**Comment by foocross** [comment]
yes that was the problem.
