### ISSUE TITLE
Odometry setup is complete, the encoders read values but they don't affect the movement of the robot

### ISSUE THREAD

**Issue by GiuliCon** [acmerobotics/road-runner-quickstart#146]
We have implemented the Two Wheel Odometry with RoadRunner on our robot. The bot follows the trajectories but with issues as expected, and the Odometry doesn't seem to affect it.

For example we held the bot suspended and ran the code. This should result in the movement motors moving at the same speed infinitely since the Odometry wheels aren't moving at all. This is not the case, the bot uses the encoders of the motors, finishes the first trajectory and continues on with the next one.

Any ideas would be greatly appreciated. Thank you!

**Comment by rbrott** [comment]
> We have implemented the Two Wheel Odometry with RoadRunner on our robot. The bot follows the trajectories but with issues as expected, and the Odometry doesn't seem to affect it.
> 
> For example we held the bot suspended and ran the code. This should result in the movement motors moving at the same speed infinitely since the Odometry wheels aren't moving at all. This is not the case, the bot uses the encoders of the motors, finishes the first trajectory and continues on with the next one.

That is to be expected. The trajectory followers move the setpoint based on time alone. However, there is closed-loop feedback for tracking that reference.

If you don't want time to determine the reference progression, you can use a path follower. There is no great path follower out of the box, but one could somewhat easily implement one by projecting the current pose onto the trajectory to determine the current reference (a la [the new GVF](https://github.com/acmerobotics/road-runner/pull/54)).

In the end, using time isn't as bad as it sounds with proper trajectory generation/motion profiling. I'd encourage you to work on your feedforward tuning/calibration and add follower PID to improve follower performance.
