### ISSUE TITLE
FTC Dashboard thinks robot is spinning in place instead of saying that it is going straight(which the bot in real life is going straight).

### ISSUE THREAD

**Issue by EliorYousefi** [acmerobotics/road-runner-quickstart#147]
hey!
I was tuning my bot's PID controller, and everything else in RoadRunner, and I got to the point where you tune the follower PID tuner using the field in the FTC dashboard, and comparing the target position to the actual position. Now, the problem is that the Dashboard and Roadrunner think that the bot is spinning in place instead of going straight. Another weird problem with it is that you can run auto codes using RoadRunner which makes your bot move let's say 30 inches, and it will move 30 inches but the final values(x, y, heading) aren't real, especially the X value... so what can be the problem and how can I fix it?

**Comment by rbrott** [comment]
> the Dashboard and Roadrunner think that the bot is spinning in place instead of going straight

Use [this op mode](https://github.com/acmerobotics/road-runner-quickstart/blob/master/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/MotorDirectionDebugger.java) to debug the motor directions. Make sure that drive commands and localization are both correct (i.e., commanding the robot forward indeed makes it move forward).
