### ISSUE TITLE
Multithreading when using Road Runner

### ISSUE THREAD

**Issue by IoanaAdrian** [acmerobotics/road-runner-quickstart#148]
I have a class that uses Road Runner's "Mecanum Drive". It follows some trajectories. While the robot is moving, I want to display some encoder values of a motor that are not related to the driving motors. For that, I have to create a separate thread. When I call the thread, the trajectories go crazy and the battery voltage drops to 10V instantly.

**Comment by rbrott** [comment]
You shouldn't need a thread in this instance. As you've discovered, threads in robot code tend to be more trouble than they're worth.

Instead, you should make use of asynchronous following and interleave calls to `drive.update()` with your own display/logging update. You should also check out [this page](https://gm0.org/en/latest/docs/software/finite-state-machines.html) on finite state machines and the simple concurrency they enable.

**Comment by IoanaAdrian** [comment]
Thank you !
