### ISSUE TITLE
LocalizationTest OpMode Issue

### ISSUE THREAD

**Issue by team16651** [acmerobotics/road-runner-quickstart#154]
The LocalizationTest OpMode doesn't correctly update the values of the telemetry, nor does the dashboard render the movement of the robot correctly.

**Comment by rbrott** [comment]
You're going to have to be more specific. The dashboard renders the motion perceived by the odometry system; perhaps there are calibration errors. Rooting out such errors is the main purpose of `LocalizationTest`.

**Comment by rbrott** [comment]
There were no substantial changes to the quickstart committed in the v7.0 upgrade. You can view the diff [here](https://github.com/acmerobotics/road-runner-quickstart/compare/82137b6d7c96a6775904840fda45d41c7f6665b0...master). The only major issue I'm aware of [this dashboard one](https://github.com/acmerobotics/ftc-dashboard/issues/67).

**Comment by team16651** [comment]
Okay, I feel quite silly here, as it turns out I forgot to set the encoder ticks per rev value, it was zero, thus nothing was being measured. Thank you so much for the hard work you do with this library.
