### ISSUE TITLE
Acmerobotics URL is offline

### ISSUE THREAD

**Issue by developer-Pavel** [acmerobotics/road-runner-quickstart#166]
Cannot get to build road-runner, the plugin website is offline.

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':TeamCode:compileDebugJavaWithJavac'.
> > Could not resolve all task dependencies for configuration ':TeamCode:debugCompileClasspath'.
>    > Could not resolve com.acmerobotics.roadrunner:core:0.5.5.
>      Required by:
>          project :TeamCode
>       > Could not resolve com.acmerobotics.roadrunner:core:0.5.5.
>          > Could not get resource 'https://maven.brott.dev/com/acmerobotics/roadrunner/core/0.5.5/core-0.5.5.pom'.
>             > Could not GET 'https://acmerobotics.z13.web.core.windows.net/com/acmerobotics/roadrunner/core/0.5.5/core-0.5.5.pom'.
>                > Connect to acmerobotics.z13.web.core.windows.net:443 [acmerobotics.z13.web.core.windows.net/127.0.0.1] failed: Connection refused: connect
>

**Comment by rbrott** [comment]
I've seen some intermittent failures before. The link is up for me now.

**Comment by developer-Pavel** [comment]
@rbrott Yes, now it's online, but when I opened the issue I cannot open it even from a web browser, so it wasn't an IDE problem. Anyway, it's fixed now, thank you for your reply.
