### ISSUE TITLE
[Q] Interpolators?

### ISSUE THREAD

**Issue by Flashman2000** [acmerobotics/road-runner-quickstart#17]
I was trying to program my own autonomous by referencing MecanumSplineFollower.java. I noticed that in the lines 

`builder
                .splineTo(new Pose2d(48, 48, Math.PI / 2), new ConstantInterpolator(0))
                .splineTo(new Pose2d(0,0,Math.PI), new LinearInterpolator(Math.PI / 2, Math.PI));`

after the splineTo coordinates are created, there are various interpolators that can be used. My question is, what is the use of each interpolator, and when do we use them? Going through the javadoc, I noticed there are about 7 different interpolators.

**Comment by rbrott** [comment]
`ConstantInterpolator` and `LinearInterpolator` are two kinds of heading interpolators. For tank drives, the nonholonomic constraint forces the heading to following the tangent/direction of the path its following. However, for holonomic drives (e.g., mecanum), the translation along the path and the heading can be changed independently. Heading interpolators allow the user to specify how the heading should change as the robot moves along the path. The docs describe briefly what each interpolator does.
