### ISSUE TITLE
quickstart2 - no good way to reverse motor encoders independently of motor

### ISSUE THREAD

**Issue by NoahBres** [acmerobotics/road-runner-quickstart#183]
From @abidingabi:

![CleanShot 2022-11-11 at 18 17 02@2x](https://user-images.githubusercontent.com/6739076/201443190-e1574f25-a7e1-4fb9-a797-a4bf1382a9db.jpg)
![CleanShot 2022-11-11 at 18 18 54@2x](https://user-images.githubusercontent.com/6739076/201443309-56d0955e-dffc-4191-bac6-16fa2bf02653.jpg)
![CleanShot 2022-11-11 at 18 17 16@2x](https://user-images.githubusercontent.com/6739076/201443210-29e66d8b-7be8-4e82-93aa-2a683ef0fe66.jpg)
![CleanShot 2022-11-11 at 18 19 30@2x](https://user-images.githubusercontent.com/6739076/201443349-b00de997-eb48-4a1a-9082-40cf4fe603eb.jpg)

**Comment by rbrott** [comment]
> no good way to reverse motor encoders independently of motor

I intend to allow that in `RawEncoder`. The logic could be more clear (negate iff `m.getDirection() != direction`), though I think it should work to apply the encoder direction independent of the motor direction. 

> you can reverse the direction of `RawEncoder`s but not `OverflowEncoder`s

True, but you can reach through the overflow encoder: `overflowEncoder.encoder.direction = ...;`

**Comment by abidingabi** [comment]
Oh, I missed that `encoder` was a public field in `OverflowEncoder` when skimming it trying to figure it how to reverse it; that rectifies the problem in a neat way.
