### ISSUE TITLE
Field is not tracking the robot's movement properly

### ISSUE THREAD

**Issue by svemula10** [acmerobotics/road-runner-quickstart#195]
When running strafeLeft(24), the robot moves left but it does not stop going left. When looking at the field on dashboard, it showed the robot moving right.
![Screenshot 2022-12-26 115206](https://user-images.githubusercontent.com/118678908/209604574-20d8af8b-766b-4033-abb3-2204811aeb51.png)

**Comment by rbrott** [comment]
You have a configuration issue. Use the motor direction debugger to make sure each motor is moving the right way.
