### ISSUE TITLE
ThreeDeadWheelLocalizer cannot be caste to MEchanumDrive$DriveLocalizer

### ISSUE THREAD

**Issue by ftcteam8645** [acmerobotics/road-runner-quickstart#202]
Cannot run LateralPushTest without getting the error "ThreeDeadWheelLocalizer cannot be caste to MEchanumDrive$DriveLocalizer".  Localizer set in MachanumDrive as follows: 
localizer = new ThreeDeadWheelLocalizer(hardwareMap,IN_PER_TICK);

**Comment by cristiioan** [comment]
So is it possible to do something to it for now.

**Comment by rbrott** [comment]
I've added `LateralRampLogger` to fill this gap.
