### ISSUE TITLE
Quickstart will not build as posted?

### ISSUE THREAD

**Issue by frankm24** [acmerobotics/road-runner-quickstart#209]
TuningOpModes refers to a bunch of non-existent op modes, errors unless it isn't commented out. Just moved over to SDK v8 plus new version of roadrunner, could be an issue on my end but I downloaded quickstart and with no changes, it won't build.

**Comment by frankm24** [comment]
Seems to be due to the logging commit

**Comment by KingTryHard1** [comment]
This seems to be correct

**Comment by KingTryHard1** [comment]
Is it possible for you to fix this soon? I got my qualifier in a couple of days and I need to get this working.

**Comment by rbrott** [comment]
My bad, I accidentally committed that file from another branch.
