### ISSUE TITLE
Parameters to pass through setLocalizer(new StandardTrackingWheelLocalizer(hardwareMap, lastTrackingEncPositions, lastTrackingEncVels));

### ISSUE THREAD

**Issue by awesomehtr1** [acmerobotics/road-runner-quickstart#214]
Hi,

What parameters do you pass in for lastTrackingEncPositions and lastTrackingEncVels? I haven't seen this before and don't know what to pass in for this. Thanks in advance!

**Comment by rbrott** [comment]
You can look at [what `SampleMecanumDrive` does](https://github.com/acmerobotics/road-runner-quickstart/blob/563b195593b5bdf0f3dc38ec509fdade29844438/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/SampleMecanumDrive.java#L131).

**Comment by awesomehtr1** [comment]
How would you figure out "lastTrackingEncPositions" and "lastTrackingEncVels"? That's the part I don't understand. Thank you.

**Comment by awesomehtr1** [comment]
Nevermind, I was being dumb. I can just set it as "setLocalizer(new StandardTrackingWheelLocalizer(hardwareMap,lastTrackingEncPositions,lastTrackingEncVels));" Thank you.
