### ISSUE TITLE
ForwardRampLogger outputs low kV (in ticks instead of inches?)

### ISSUE THREAD

**Issue by j5155** [acmerobotics/road-runner-quickstart#219]
https://discord.com/channels/225450307654647808/1092714703844823061/1092904193771196518
This seems to be saying that ForwardRampLogger outputs a kV in ticks(?) rather then the inches that are expected, and dividing kV by in_per_tick fixes it. 
I also got a very low kV from the logger (0.00010209...) and converting it gave a much more reasonable estimate, though I looked at the code and it was difficult to tell what units each was expecting (which might be what led to this confusion).

**Comment by rbrott** [comment]
I did intend for the units to be ticks in both the tuner and the top-level variables. It's then in inches at the `MotorFeedforward` level. I hope the units are consistent with that convention after https://github.com/acmerobotics/road-runner-quickstart/commit/491bb4212304468bb68f29424293ffbe111fac4f.

It is confusing to have different units in different places. Comments/variable name changes are probably in order.
