### ISSUE TITLE
ManualFeedBackTuner error on lineToX

### ISSUE THREAD

**Issue by Parvel** [acmerobotics/road-runner-quickstart#224]
Trying the rr-1.0.0-beta1 and the ManualFeedBackTuner seems to stuck on the call of lineToX.
Error reported as:             "Path tangent orthogonal to the x-axis, try using lineToY() instead"

Checked this require is added since rr1.0 last year in PositionPathSeqBuilder for lineToX and lineToY. But due to my limited context I'm sure what's the design consideration of doing the check:
` 
require(abs(nextBeginTangent.real) > 1e-6) {
        "Path tangent orthogonal to the x-axis, try using lineToY() instead"
}
`

It seems like unless someone calling setTangent explicitly like it is in strafeTo, this nextBeginTangent check could always blocking the lineTo logic?

Wondering what could be the right sequence or changes to execute the manual feedback tuner? Thanks!

**Comment by rbrott** [comment]
I believe this is fixed in `1.0.0-beta2`. I cut the release a few weeks ago but only recently pushed (and still haven't written proper release notes).
