### ISSUE TITLE
[Q] Same PID coefficients for all motors on the drivetrain?

### ISSUE THREAD

**Issue by Calvin-Xu** [acmerobotics/road-runner-quickstart#23]
We are wondering if there is a reason that the same PID coefficients are set for all motors on the drivetrain (for example `setPIDCoefficients` in `SampleMecanumDriveREVOptimized`). It seems to us that on our drivetrain each motor/wheel has a different error and should be tuned separately?

**Comment by rbrott** [comment]
For common drive configurations, the load on each motor should be pretty much the same, so the same coefficients should work for all of them. Keep in mind that each motor has its own control loop and error even if the coefficients are the same. If you have a particularly skewed weight distribution or a special hardware setup, you can definitely tune the motor coefficients separately.

**Comment by Calvin-Xu** [comment]
Thank you for the clarification!
