### ISSUE TITLE
com.acmerobotics.roadrunner imports don't work

### ISSUE THREAD

**Issue by Abraham001l** [acmerobotics/road-runner-quickstart#233]
I cloned the repositories main branch but for some reason after gradle building imports from com.acmerobotics.roadrunner don't work.

**Comment by Abraham001l** [comment]
my acme robotics implementation on TeamCode is "com.acmerobotics.roadrunner:ftc:0.1.3"

**Comment by rbrott** [comment]
I believe the transitive dependencies in the [pom](https://acmerobotics.z13.web.core.windows.net/com/acmerobotics/roadrunner/ftc/0.1.3/ftc-0.1.3.pom) are correct, and the project builds fine for me locally.

I suspect some combination of [invalidating caches](https://www.jetbrains.com/help/idea/invalidate-caches.html) and syncing with Gradle (Click Sync Project with Gradle Files ![image](https://github.com/acmerobotics/road-runner-quickstart/assets/6677314/813785db-c65d-47a8-9b3b-94ad7a9867ee)) will get Android Studio to recognize the imports.

**Comment by Abraham001l** [comment]
For some reason changing to the latest version of android studio got the "com.acmerobotics.roadrunner:ftc:0.1.3" implementation working. I was peviously on version Dolphin (2021.3.1).
