### ISSUE TITLE
Line of Best Fit Doesn't Appear in RR Drive Encoder Angular Ramp Regression Logger 

### ISSUE THREAD

**Issue by TCoppola6** [acmerobotics/road-runner-quickstart#241]
When trying to log the Angular Ramp regression I am able to receive the points on the graph, but it does not generate a line of best fit. The track width also displays as NaN.

![image](https://github.com/acmerobotics/road-runner-quickstart/assets/113483276/b019b839-f786-45b2-aa89-72b1dcd9d76b)

**Comment by rbrott** [comment]
Duplicate of #234. Try updating to `0.1.6`.
