### ISSUE TITLE
Field Relative Driving

### ISSUE THREAD

**Issue by EddieDL** [acmerobotics/road-runner-quickstart#246]
@rbrott  I saw an interesting comment you made on another issue (https://github.com/acmerobotics/road-runner/issues/90#issuecomment-1722674965). You provide an interesting implementation of field centric driving. If I understand correctly this code will allow you to drive the robot relative to the field orientation, but will not incorporate where the drivers position is.

I believe to address this you could simply have logic that would further adjust this Vector2d based on if you are blue or red alliance. Do you have any suggestion on how you would do that? Do you just need to further rotate the Vector2d?

```
Vector2d input = new Vector2d(
  -gamepad1.left_stick_y * speed,
  -gamepad1.left_stick_x * speed
);

if (fieldCentric) {
  input = drive.pose.heading.inverse().times(
    new Vector2d(-input.x, input.y));
}
```

**Comment by rbrott** [comment]
> If I understand correctly this code will allow you to drive the robot relative to the field orientation, but will not incorporate where the drivers position is.

Correct.

> I believe to address this you could simply have logic that would further adjust this Vector2d based on if you are blue or red alliance. Do you have any suggestion on how you would do that? Do you just need to further rotate the Vector2d?

Yes, you can apply an additional rotation. The easiest way to accomplish that is conditionally replace `drive.pose.heading` with `drive.pose.heading.plus(Math.PI)`.
