### ISSUE TITLE
Latest Button Does Not Function Properly

### ISSUE THREAD

**Issue by ExternalYelu** [acmerobotics/road-runner-quickstart#248]
Hello,
The Road Runner latest button does not work for us when we try to get a graph after running the ForwardRampLogger OpMode. We were able to find the .json file for the graphs by looking through the storage of the control hub, but when pressing the latest button, we receive the message "no data file found." In addition, when running the ManualFeedforwardTuner OpMode we can see the instantaneous values for vref, v0, and kA in the telemetry, but no graph shows up for v0 and vref when we run the opmode with the graph. 

Copy the links into a webpage to see the pictures below.

https://github.com/acmerobotics/road-runner-quickstart/assets/113480332/b7c981e4-4ff2-45e6-a412-621f1a8ef21f

https://github.com/acmerobotics/road-runner-quickstart/assets/113480332/e3545366-f433-4ac2-967d-671c075a5eb3

**Comment by rbrott** [comment]
> Hello, The Road Runner latest button does not work for us when we try to get a graph after running the ForwardRampLogger OpMode. 

Next time can you try exiting out of the graph and re-plotting? I see the telemetry values in the other widget, so the data must be coming into dash.

> We were able to find the .json file for the graphs by looking through the storage of the control hub, but when pressing the latest button, we receive the message "no data file found."

Which library version do you have? At what path did you find the files?
