### ISSUE TITLE
LocalizationTest outputting Nan for robot position

### ISSUE THREAD

**Issue by jamesgu888** [acmerobotics/road-runner-quickstart#253]
Renamed encoder names to the DCmotor they were attached to
![Screenshot 2023-10-01 151517](https://github.com/acmerobotics/road-runner-quickstart/assets/139718358/d7a7395b-82e8-4b1a-b3ec-b72983a19139)

Running LocalizationTest shows NaN values in telemetry. Any idea why it isn't receiving the encoder values?
![image](https://github.com/acmerobotics/road-runner-quickstart/assets/139718358/5603d62b-bdb3-4dc9-aff1-acffc909ab4c)

**Comment by rbrott** [comment]
Have you set the encoder positions? That's (unfortunately) expected with the default encoder positions.

**Comment by SuhasB1** [comment]
I have the same problem. What do you mean by "setting the encoder positions." Do you mind elaborating on this.

**Comment by jamesgu888** [comment]
what rbrott said fixed my robot at least. check the threedeadwheellocalizer if you are using that and you should have to configure the variables par0YTicks, par1YTicks, and perpXTicks. 
![image](https://github.com/acmerobotics/road-runner-quickstart/assets/139718358/a10c66e6-7421-453f-951c-2af6a6381222)
configure these variables by running AngularRampLogger (when u go to the site there should be multiple graphs, one for trackwidthlength and other 3 for the encoder positions)
