### ISSUE TITLE
Suggest to clarify documentation about reversing motors and encoders and IMU in Dive Classes basic hardware configuration doc.

### ISSUE THREAD

**Issue by teamhazmat13201** [acmerobotics/road-runner-quickstart#257]
The documentation in Drive Classes secion in https://rr.brott.dev/docs/v1-0/tuning/ reads : Reverse any motors running in the wrong direction with setDirection(...), and do the same for corresponding drive encoders as well.The direction of each Encoder is independent of the DcMotorEx it’s created with. Changing the direction of an Encoder has no effect on the direction of its associated DcMotorEx (and vice versa).

The statement is accurate, but we still missed in code that we had to change the direction for both the motors and encoders separately! Just was not used to thinking like this from 0.5.6 version.

Could you update it say: 
______________
Reverse encoder direction in MecanumDrive.class : DriveLocalizer Class: DriveLocalizer()
ex: rightRear.setDirection(DcMotorEx.Direction.REVERSE);
            rightFront.setDirection(DcMotorEx.Direction.REVERSE);
AND
Reverse motor direction in MecanumDrive.class : MecanumDrive(...)
ex: rightRear.setDirection(DcMotorEx.Direction.REVERSE);
            rightFront.setDirection(DcMotorEx.Direction.REVERSE);

Note: Changing only motor direction will "pass" the MotorDirectionDebugger test, but when you do ForwardPush Test, the ticks counter will be close to 0.
_______________

Also, please add statement to update IMU orientation information: 
______________
Update IMU orientation information based on logo and USB facing directions. Use UP / DOWN / LEFT / RIGHT / FORWARD / BACKWARDin the code snippet below in  MecanumDrive.class : MecanumDrive(...)
        IMU.Parameters parameters = new IMU.Parameters(new RevHubOrientationOnRobot(
                RevHubOrientationOnRobot.LogoFacingDirection.UP,
                RevHubOrientationOnRobot.UsbFacingDirection.FORWARD));
______________

Would be great to have a comment in the code for the user to notice these too.
 
Thanks,

**Comment by rbrott** [comment]
I added some more instructions to the tuning page as well as some TODO comments in the code (like the old quickstart).
