### ISSUE TITLE
How to tune axial and lateral gains using ManualFeedbackTuner?

### ISSUE THREAD

**Issue by madacker** [acmerobotics/road-runner-quickstart#259]
The doc implies that ManualFeedbackTuner is used to tune forward, strafe and rotate but given that the test drives only forward and backwards I'm not sure how to tune axial and lateral gains. Maybe I'm missing something obvious?

Will the strafe and rotate tuning opmode tests be added back to allow this? Or maybe ManualFeedbackTuner will do a square again? (On Mecanum drives it rotates 180 degrees every second corner of the square?)

**Comment by rbrott** [comment]
> The doc implies that ManualFeedbackTuner is used to tune forward, strafe and rotate but given that the test drives only forward and backwards I'm not sure how to tune axial and lateral gains. Maybe I'm missing something obvious?

You're not really missing anything. Some people found it easier to control and reset the robot when it's just moving back and forth. You also don't need as much tile space. Heading disturbances are introduced by physically pushing the robot and seeing it react (even though that's not quite the same disturbance as a turn). But there's nothing special about this pattern, and you're free to tune the feedback parameters with whatever trajectory you like.

> Will the strafe and rotate tuning opmode tests be added back to allow this? Or maybe ManualFeedbackTuner will do a square again? (On Mecanum drives it rotates 180 degrees every second corner of the square?)

I'll think about this, though I'd be happier if teams would write whatever routines suit them best.
