### ISSUE TITLE
Getting "index: 0 size: 0" error when running LateralPushTest OpMode

### ISSUE THREAD

**Issue by rockit456** [acmerobotics/road-runner-quickstart#261]
I was able to complete the forward push test but when I got to the lateral push test we started getting errors. Everything is updated and I'm having trouble figuring out where the error is coming from.

**Comment by MartianBinonwangan** [comment]
I also had the same error earlier. What's you're localizer setting? Are you using an independent odometry system or the drive encoders?

**Comment by rockit456** [comment]
We are using 3 dead wheels.

**Comment by MartianBinonwangan** [comment]
You won’t be able to use the tuner to tune your lateral inch per tick count since you’re using Odom. You’ll tune it when you run the lateral ramp logger test. This test is only for teams using Mecanum drive encoders only.

**Comment by rockit456** [comment]
Thank you!
