### ISSUE TITLE
IllegalArgumentException in FollowTrajectoryAction

### ISSUE THREAD

**Issue by kcjones** [acmerobotics/road-runner-quickstart#267]
We are seeing the below IllegalArgumentException in FollowTrajectoryAction. 

I have a method that generates and runs an ActionSequence when pressing a button on the controller. This exception trips on the 1st through 5th press. Any ideas on what may be occurring or if there is a better approach to this?

This sequence generates the exception:
`        drive.updatePoseEstimate();
        Actions.runBlocking(drive.actionBuilder(drive.pose)
                .strafeToLinearHeading(new Vector2d(
                                drive.pose.position.x - 5,
                                drive.pose.position.y - 5
                        ),
                        Math.toRadians(45) + drive.pose.heading.log()
                ).build());
`

Relatedly, can you recommend a method for canceling the trajectory midway? We want to be able to interrupt it if a driver tries moving manually. My current plan is to add a condition in FollowTrajectoryAction that zeros motor power and returns false.

- Kevin
----------

10-18 08:04:06.210   978  1191 E OpModeManager: java.lang.IllegalArgumentException: Failed requirement.
10-18 08:04:06.212   978  1191 E OpModeManager: 	at com.acmerobotics.roadrunner.Math.range(Math.kt:43)
10-18 08:04:06.216   978  1191 E OpModeManager: 	at org.firstinspires.ftc.teamcode.roadrunner.MecanumDrive$FollowTrajectoryAction.<init>(MecanumDrive.java:241)
10-18 08:04:06.221   978  1191 E OpModeManager: 	at org.firstinspires.ftc.teamcode.roadrunner.MecanumDrive.lambda$actionBuilder$1$org-firstinspires-ftc-teamcode-roadrunner-MecanumDrive(MecanumDrive.java:450)
10-18 08:04:06.224   978  1191 E OpModeManager: 	at org.firstinspires.ftc.teamcode.roadrunner.MecanumDrive$$ExternalSyntheticLambda0.make(D8$$SyntheticClass)
10-18 08:04:06.227   978  1191 E OpModeManager: 	at com.acmerobotics.roadrunner.TrajectoryActionBuilder$endTrajectory$1.invoke(Actions.kt:264)
10-18 08:04:06.229   978  1191 E OpModeManager: 	at com.acmerobotics.roadrunner.TrajectoryActionBuilder$endTrajectory$1.invoke(Actions.kt:259)
10-18 08:04:06.234   978  1191 E OpModeManager: 	at com.acmerobotics.roadrunner.TrajectoryActionBuilder.build(Actions.kt:740)
10-18 08:04:06.235   978  1191 E OpModeManager: 	at org.firstinspires.ftc.teamcode.hardware.Robot.driveToAprilTag(Robot.java:267)
10-18 08:04:06.238   978  1191 E OpModeManager: 	at org.firstinspires.ftc.teamcode.opmode.TeleOp10644.runOpMode(TeleOp10644.java:258)
10-18 08:04:06.240   978  1191 E OpModeManager: 	at com.qualcomm.robotcore.eventloop.opmode.LinearOpMode.internalRunOpMode(LinearOpMode.java:199)
10-18 08:04:06.248   978  1191 E OpModeManager: 	at com.qualcomm.robotcore.eventloop.opmode.OpModeInternal.lambda$internalInit$1$com-qualcomm-robotcore-eventloop-opmode-OpModeInternal(OpModeInternal.java:181)
10-18 08:04:06.251   978  1191 E OpModeManager: 	at com.qualcomm.robotcore.eventloop.opmode.OpModeInternal$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
10-18 08:04:06.252   978  1191 E OpModeManager: 	at com.qualcomm.robotcore.util.ThreadPool.logThreadLifeCycle(ThreadPool.java:737)
10-18 08:04:06.253   978  1191 E OpModeManager: 	at com.qualcomm.robotcore.eventloop.opmode.OpModeInternal.lambda$internalInit$2$com-qualcomm-robotcore-eventloop-opmode-OpModeInternal(OpModeInternal.java:179)
10-18 08:04:06.255   978  1191 E OpModeManager: 	at com.qualcomm.robotcore.eventloop.opmode.OpModeInternal$$ExternalSyntheticLambda2.run(D8$$SyntheticClass)
10-18 08:04:06.255   978  1191 E OpModeManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-18 08:04:06.256   978  1191 E OpModeManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-18 08:04:06.257   978  1191 E OpModeManager: 	at com.qualcomm.robotcore.util.ThreadPool$ThreadFactoryImpl$1.run(ThreadPool.java:793)
10-18 08:04:06.257   978  1191 E OpModeManager: 	at java.lang.Thread.run(Thread.java:761)

**Comment by rbrott** [comment]
> We are seeing the below IllegalArgumentException in FollowTrajectoryAction.

https://github.com/acmerobotics/road-runner-quickstart/commit/e291d590a6105444a03191a0eb054a2a6196a4bb should fix the posted exception. 

> Relatedly, can you recommend a method for canceling the trajectory midway? We want to be able to interrupt it if a driver tries moving manually. My current plan is to add a condition in FollowTrajectoryAction that zeros motor power and returns false.

Don't call `Actions.runBlocking()` and instead call [`run()`](https://rr.brott.dev/docs/v1-0-0-beta1/actions/kdoc/actions/com.acmerobotics.roadrunner/-action/) repeatedly until you want to cancel or it finishes (returns `false`).
