### ISSUE TITLE
Request for sample code using Velocity Constraints

### ISSUE THREAD

**Issue by teamhazmat13201** [acmerobotics/road-runner-quickstart#269]
Could you provide a sample line of code for using Velocity constraints in .splineto.. or .lineto..  methods, It isn't very obvious to us like it was with .setVelocityConstraints in the 0.5.6.

**Comment by rbrott** [comment]
Most `TrajectoryActionBuilder` methods accept velocity and acceleration constraint overrides (for example, here's [`lineToX`](https://rr.brott.dev/docs/v1-0-0-beta1/actions/kdoc/actions/com.acmerobotics.roadrunner/-trajectory-action-builder/#679012707%2FFunctions%2F-50674542).
