### ISSUE TITLE
Problems finding ExpansionHubEx

### ISSUE THREAD

**Issue by EddieDL** [acmerobotics/road-runner-quickstart#27]
I am not sure this is the right place to ask this. If it is not, I will post to one of the other GitHub repos for the applicable related library.

It seems like the code to retrieve the expansionhub is "flaky". If we deploy new code, the app crashes, etc. you can no longer find the expansionhub unless you restart the robot and app. 

Is there something we are doing wrong or is it just the cost of being able to do "bulk reads"?

**Comment by rbrott** [comment]
This is an issue with https://github.com/OpenFTC/RevExtensions2

**Comment by rbrott** [comment]
You can try downgrading RE2 to 1.1 (i.e., replace `implementation 'org.openftc:rev-extensions-2:1.2'` with `implementation 'org.openftc:rev-extensions-2:1.1'` in `TeamCode/build.release.gradle`) and add `RevExtensions2.init()` to the beginning of the op modes.

**Comment by EddieDL** [comment]
This is an interesting idea. I think I will try this out when I get a chance.
