### ISSUE TITLE
Having trouble uploading the data to RR Lateral Ramp Regression

### ISSUE THREAD

**Issue by rockit456** [acmerobotics/road-runner-quickstart#273]
I have pressed latest multiple times and reran the code multiple times but no data is showing up on the graph. Does anyone have any ideas to fix this?

**Comment by Zw96042** [comment]
I believe you have to input the values that it is asking for above the latest button.

**Comment by rockit456** [comment]
I have inputed kS, kV, and inchesPerTick

**Comment by rbrott** [comment]
Can you [open the console](https://developer.chrome.com/docs/devtools/open/#shortcuts) and report any messages?

Also what version of the libraries are you running?

**Comment by raghuponugoti** [comment]
We had the same problem. In the documentation it says for (mecanum dead wheels only) so was wasnt sure if it is for Three dead wheel Odometry as well?
Didnt had issues to any other Logger. 
We are using 0.1.8

**Comment by rockit456** [comment]
No errors stood out in the console and we are using the latest version of the quickstart

**Comment by rockit456** [comment]
This was working a couple weeks ago in an older version
