### ISSUE TITLE
Stale link for Quickstart in 1.0 installation docs

### ISSUE THREAD

**Issue by madacker** [acmerobotics/road-runner-quickstart#276]
The Quickstart GitHub page link should probably be https://github.com/acmerobotics/road-runner-quickstart instead of https://github.com/acmerobotics/road-runner-quickstart/tree/quickstart2.

**Comment by mikeream** [comment]
Agree that the quickstart2 link is not working, but not sure the link you have posted is correct either since it seems like it has an old version of roadrunner in the build.gradle file.  Is there a quickstart2?
