### ISSUE TITLE
ForwardPushTest

### ISSUE THREAD

**Issue by TeamSandman** [acmerobotics/road-runner-quickstart#278]
We are using a three dead wheel localizer. When we run the forward push test one encoder is reversed leading to very low tick counts. When we run the ForwardRampLogger we get a V-shaped graph. I read through "RawEncoder applyDirection seems to overcorrect currentPosition #234" and tried this suggestion: "After investigating the code that @rbrott calls out. We just called 'per.setDirection(REVERSED)" except I used par1 instead of per1, but REVERSED doesn't seem to be an allowed option.  I also saw the suggestion to plug the dead wheel encoders into the non-reversed drive motor ports. Do we not need the encoders for the drive motors if using the dead wheels? 
Please forgive any lack of information, we are not strong enough in our coding to fully understand the issue. 
Thanks from 16312 Team Sandman
[forward-ramp-1698612694106 (2).json](https://github.com/acmerobotics/road-runner-quickstart/files/13211808/forward-ramp-1698612694106.2.json)

**Comment by rbrott** [comment]
> but REVERSED doesn't seem to be an allowed option. 

`REVERSED` isn't an option, but `DcMotorSimple.Direction.REVERSE` is. See [this concept op mode](https://github.com/FIRST-Tech-Challenge/FtcRobotController/blob/f326c0d033b69a476dea0a06bc394103e504a0ca/FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptRevSPARKMini.java#L72). 

> I also saw the suggestion to plug the dead wheel encoders into the non-reversed drive motor ports. 

This will not solve the problem. RR separates the direction of each encoder from the direction of the corresponding motor.

Please use the `MecanumMotorDirectionDebugger` op mode to check that the directions are all correct (both motors and encoders).
