### ISSUE TITLE
Actions.runBlocking

### ISSUE THREAD

**Issue by TheMujdii3** [acmerobotics/road-runner-quickstart#280]
In my autonomous code when im trying to run Actions.runblocking(drive.....()
.lineToX(20),
.build);
nothing happens.One week ago when i did the calibration the tuning modes worked now they are not along wing my auto.Any ideas?

**Comment by rbrott** [comment]
Maybe you didn't record the parameters from dash in your code file when you finished? Would be great to get a log.

**Comment by TheMujdii3** [comment]
I did.the runblocking method is not working even when im trying to call it in autonomy
