### ISSUE TITLE
What are the positional gains and velocity gains needed to tune Feedforward?

### ISSUE THREAD

**Issue by NoahMarvelsofMAS** [acmerobotics/road-runner-quickstart#284]
I can't find the params in the mecanum config.

**Comment by rbrott** [comment]
> What are the positional gains and velocity gains needed to tune Feedforward?

This question conflates feedforward and feedback. 
* The feedforward model describes how velocities and accelerations can be converted into motor voltages. Its parameters are 
  ```
        // feedforward parameters (in tick units)
        public double kS = 0;
        public double kV = 0;
        public double kA = 0;
  ```
* The feedback controller take position and velocity errors and computes corrections to get the robot toward the desired state. The parameters are
  ```
        // path controller gains
        public double axialGain = 0.0;
        public double lateralGain = 0.0;
        public double headingGain = 0.0; // shared with turn


        public double axialVelGain = 0.0;
        public double lateralVelGain = 0.0;
        public double headingVelGain = 0.0; // shared with turn
```
