### ISSUE TITLE
[Q] Motor encoder PID & velocity PID

### ISSUE THREAD

**Issue by Calvin-Xu** [acmerobotics/road-runner-quickstart#29]
This is a conceptual question: what is the role of the drivetrain PID loop?

We understand that the process of tuning the drivetrain PID coefficients with `DriveVelocityPIDTuner` is matching the measured velocities of each wheel to the target velocity according to the motion profile. 

We read that the built-in velocity PID (`RUN_USING_ENCODER`) tries to match the motor shaft's rotational velocity to the input power given ("In the `DcMotor.RunMode.RUN_USING_ENCODER` mode, the controller uses an onboard velocity PID controller, and the power is instead a scaled velocity.").

Since the wheel velocities are themselves calculated from the encoder readings on the drive wheels, we are wondering why the internal PID cannot handle it, and we need a separate closed loop for the drivetrain (i.e., if the built-in velocity PID makes the motors turn at the right rotational velocity, what more needs to be done?). Of course our past experience suggests that this is not true, but we just cannot think it through. Any explanation would be of great help to our team!

**Comment by rbrott** [comment]
>Since the wheel velocities are themselves calculated from the encoder readings on the drive wheels, we are wondering why the internal PID cannot handle it, and we need a separate closed loop for the drivetrain (i.e., if the built-in velocity PID makes the motors turn at the right rotational velocity, what more needs to be done?). 

Your reasoning is correct. `DriveVelocityPIDTuner` tunes the built-in PID coefficients; there is no second velocity PID loop. The default coefficients can work OK for some robots, although it doesn't hurt to check. The more error you can eliminate in each step, the better.

**Comment by Calvin-Xu** [comment]
Thank you! Do you know if there is a way to query the default PID coefficients, as a starting point?

**Comment by rbrott** [comment]
The tuning routine queries them initially. Just open the dashboard *after you start the op mode*.
