### ISSUE TITLE
Using Encoders and X and Y in localization test is outputting NaN

### ISSUE THREAD

**Issue by jamesgu888** [acmerobotics/road-runner-quickstart#290]
the localizer is set to DriveLocalizer() in MecanumDrive and isn't requiring odometry pod location (using drive encoders)

finished setting up all the tick values and kv/ks but after running ManualFeedbackTuner the robot is not moving while vref is changing

ran localization test and X and Y values are outputting NaN but the heading actually gives a value

any reason why the robot isnt moving?

**Comment by rbrott** [comment]
> ran localization test and X and Y values are outputting NaN but the heading actually gives a value

Any values being NaN here will make the commanded power NaN. Is your lateral multiplier zero?
