### ISSUE TITLE
Drive Constants Issues with the QuickStart.

### ISSUE THREAD

**Issue by Taylor-Nilsen** [acmerobotics/road-runner-quickstart#293]
you must include this import when using the quick start or importing to your project. 
`import com.qualcomm.hardware.rev.RevHubOrientationOnRobot;`

you must also include this block of code in the drive constants file, about line 95, if you generate your drive constants.
`/*
     * Adjust the orientations here to match your robot. See the FTC SDK documentation for details.
     */
    public static RevHubOrientationOnRobot.LogoFacingDirection LOGO_FACING_DIR =
            RevHubOrientationOnRobot.LogoFacingDirection.UP;
    public static RevHubOrientationOnRobot.UsbFacingDirection USB_FACING_DIR =
            RevHubOrientationOnRobot.UsbFacingDirection.FORWARD;`

**Comment by rbrott** [comment]
Official RR doesn't support generating `DriveConstants`. You should file this issue elsewhere.
