### ISSUE TITLE
Can someone clarify how to get dead wheel positions for 3 wheel odometry?

### ISSUE THREAD

**Issue by ayoda1122** [acmerobotics/road-runner-quickstart#296]
I am confused about how to get the position values for the dead wheels in tick units. Do I just measure and then multiply by inches per tick?

**Comment by rbrott** [comment]
Do not measure. `AngularRampLogger` will do it for you when you get to that step: https://rr.brott.dev/docs/v1-0/tuning/#angularramplogger.

**Comment by ayoda1122** [comment]
Thank you it makes a lot more sense when I scroll down.
