### ISSUE TITLE
Spline Test Went Wild

### ISSUE THREAD

**Issue by 1248013** [acmerobotics/road-runner-quickstart#298]
Started tuning two-wheel odometry and it went fairly smooth for the most part, I've seen many other people have issues with the manualfeedback tuner yet I did not have this problem and I got all the gains and such just fine. The last test was the spline test and when I ran it, it took the left turn, and instead of completing the spline it ran in reverse and had a mind of its own. Not sure whats wrong with it as the manualfeedback tuner ran straight just fine along with the rest of the tuning but it seems to have a stroke when completing a spline. Any tips for troubleshooting?

**Comment by rbrott** [comment]
Please retrieve a robot log (see http://localhost:1313/docs/v1-0/tuning/#getting-help)
