### ISSUE TITLE
Manual FeedBack Tuner Problems RR 1.0

### ISSUE THREAD

**Issue by AwesomePerson01** [acmerobotics/road-runner-quickstart#302]
We are using a mecanum drivetrain and 3 deadwheels.  We started tuning the robot, and it was going well until we reached the manual feedback tuner part of tuning.  We originally had a problem where the robot would have a small seizure but fixed that.  Now instead of going back and forth it goes forward for a second and starts strafing.  If anyone has any advice please let me know.  Thanks!

**Comment by rbrott** [comment]
Sounds like #303. Please try to retrieve a robot log, and we'll continue the conversation over there.
