### ISSUE TITLE
Quintic custom splines not working

### ISSUE THREAD

**Issue by NoahMarvelsofMAS** [acmerobotics/road-runner-quickstart#304]
### RR FTC Version

1.0.0

### Observed Behavior

```
QuinticSpline spline = new QuinticSpline(
    new QuinticSpline.Waypoint(0, 0, 20, 20),
    new QuinticSpline.Waypoint(30, 15, -30, 10)
);
```
This code is giving me so many ide errors how would I do this in 1.0.0

**Comment by rbrott** [comment]
The internal API has changed from 0.5.x to 1.0. Knock yourself out: https://rr.brott.dev/docs/v1-0-0-beta1/core/kdoc/core/com.acmerobotics.roadrunner/-quintic-spline2/
