### ISSUE TITLE
ConceptTensorFlowObjectDetetion:Camera recognition failed

### ISSUE THREAD

**Issue by lovezfy** [acmerobotics/road-runner-quickstart#317]
Run ConceptTensorFlowObjectDetetion. But this camera is slow to recognize pixel. In a minute, I might get one successful recognition, and it's not good.  Do you have similar problems? Can you give me some advice?

**Comment by rbrott** [comment]
Sorry, this forum is for questions relating to Road Runner only. Try [r/ftc](https://www.reddit.com/r/FTC/) or the [FTC Discord](https://discord.com/invite/first-tech-challenge).
