### ISSUE TITLE
AngularRampLogger doesn't automatically graph it's results

### ISSUE THREAD

**Issue by ftc19853** [acmerobotics/road-runner-quickstart#320]
We recently used the AngularRampLogger and it was working with no problem, spinning around and "updating" the graph when the button was pressed. We updated to 1.0.0Beta4 and now it doesn't show anything on the graph.
![image](https://github.com/acmerobotics/road-runner/assets/97846945/45e1d6ba-1268-42d7-b852-6c09a8533ab5)
It also shows that whenever we actually import any file as well.

**Comment by rbrott** [comment]
I don't believe the update should have changed anything. Can you please download the tuning file and attach it here?

**Comment by ftc19853** [comment]
I don't think this is the latest one(we switch pcs some time:)
[angular-ramp-1699736019208.json](https://github.com/acmerobotics/road-runner-quickstart/files/13519730/angular-ramp-1699736019208.json)

**Comment by rbrott** [comment]
Can you report any errors in the web console? It all looks fine to me locally:
![Screenshot 2023-11-30 at 20-08-54 RR Drive Encoder Angular Ramp Regression](https://github.com/acmerobotics/road-runner-quickstart/assets/6677314/f1caefd1-0ab7-41b9-a84f-baaaf077dc08)

**Comment by ftc19853** [comment]
is there supposed to be a clump at the end?
![image](https://github.com/acmerobotics/road-runner-quickstart/assets/97846945/e16da30f-6f42-4f8d-a58c-05f93cbbdaa4)

**Comment by rbrott** [comment]
Yes, if you leave the logger running after it finishes the ramp then it will accumulate samples there.
