### ISSUE TITLE
Plotty.js pages (forward-ramp, lateral-ramp, dead-wheel-angular-ramp etc.) include and exclude buttons don't work as expected

### ISSUE THREAD

**Issue by ToddInIowa** [acmerobotics/road-runner-quickstart#323]
### RR FTC Version

0.1.9

### Observed Behavior

When a box is drawn on the plot and you click the exclude button the whole graph looks to be excluded, the slope does change slightly.  When I press the include button nothing changes, even though the slope should change.
![image](https://github.com/acmerobotics/road-runner-quickstart/assets/42328950/3204ebfd-ce88-435e-9ffa-c45cb2fed115)
Screenshot of an attempt to change the slope aggressively via include.

![image](https://github.com/acmerobotics/road-runner-quickstart/assets/42328950/14920ad7-46b2-465b-b575-41c03565f540)
Screenshot trying to exclude some plots.

Chrome version 119.0.6045.160
Edge version 119.0.2151.97

I didn't see any error in the Chrome debugging console.

### Tuning Files

[lateral-ramp-1701752252825.json](https://github.com/acmerobotics/road-runner-quickstart/files/13555254/lateral-ramp-1701752252825.json)
[angular-ramp-1701753355254.json](https://github.com/acmerobotics/road-runner-quickstart/files/13555255/angular-ramp-1701753355254.json)
[forward-ramp-1701752149737.json](https://github.com/acmerobotics/road-runner-quickstart/files/13555256/forward-ramp-1701752149737.json)

**Comment by rbrott** [comment]
The plotly interface is confusing. You won't see the final selection after including/excluding until you exit the box selection tool. I usually exit by double clicking on the plot. Here's a demo I recorded that hopefully shows how it works:

https://github.com/acmerobotics/road-runner-quickstart/assets/6677314/bfe57348-9c82-49c1-b211-7fc62b5bc3c2

**Comment by rbrott** [comment]
I see what you mean about the controls though. I just released a new version of the tuning tools that downgrades Plotly to restore the old (desired) select behavior.
