### ISSUE TITLE
lineToY not working

### ISSUE THREAD

**Issue by ToddInIowa** [acmerobotics/road-runner-quickstart#325]
### RR FTC Version

0.1.9

### Observed Behavior

We are trying to run lineToY and we come up with this error: "Path tangent orthogonal to the y-axis, try using lineToX() instead". 
` Actions.runBlocking(
                drive.actionBuilder(drive.pose)
                        .lineToY(20)
                        .build());`

**Comment by rbrott** [comment]
`lineToY()` draw a line along the current tangent direction until it hits a point with the given y-coordinate. 

I'm assuming that `drive.pose` has a heading of zero. The initial tangent used by the builder is the initial heading. So no matter how far you go along the tangent, the y-coordinate remains the same.

Try adding `setTangent(0.0)` before `lineToY()`.
