### ISSUE TITLE
how to change trajectory speed on rr 1.0.0?

### ISSUE THREAD

**Issue by jamesgu888** [acmerobotics/road-runner-quickstart#331]
how to change velconstraint on path movement such as .splineTo(new Vector2d(10, 15), ________)?

**Comment by Vector5233** [comment]
Similar question.  The velocity constraints have substantially changed from v 0.5.x and I’m unclear how to use eg MaxVelConstraint.  It seems to require a path as an argument.  So would we first construct the trajectory, then pass a MaxVelConstraint to runBlocking?

**Comment by rbrott** [comment]
Changing the trajectory speed from the builders works pretty much the same as RR 0.5.x. I wrote a short [guide](https://rr.brott.dev/docs/v1-0/guides/variable-constraints/) on the basics.
