### ISSUE TITLE
I am getting an hardware map is outdated error when I init my drive.

### ISSUE THREAD

**Issue by ayoda1122** [acmerobotics/road-runner-quickstart#333]
### RR FTC Version

0.1.9

### Observed Behavior

I have my declaration in my auto base that is extended to my opmodes

**Comment by rbrott** [comment]
Can you post the exact error message? Do you mean that your Lynx firmware is outdated?

**Comment by ayoda1122** [comment]
Yes, that was the error. But at the moment I cant run it to get the error again

**Comment by rbrott** [comment]
Okay then you need to follow the instructions here: https://ftc-docs.firstinspires.org/en/latest/ftc_sdk/updating/hub_firmware/Updating-Hub-Firmware.html

**Comment by ayoda1122** [comment]
Sorry just found the error message I was thinking of another error here is the current error
![IMG_2044](https://github.com/acmerobotics/road-runner-quickstart/assets/145617680/32512338-914c-4419-a795-c59129c7d9a5)

**Comment by rbrott** [comment]
You're constructing the drive object too early. Wait to construct it until `runOpMode()`/`init()`.
