### ISSUE TITLE
LateralRampLogger does not show graph

### ISSUE THREAD

**Issue by Shooter913b** [acmerobotics/road-runner-quickstart#335]
We tried to run LateralRampLogger after getting values for kS, kV, and inPerTick but no graph appeared. This is the json file we got after downloading our data, but this also does not show anything when we try to graph it.
[lateral-ramp-1702757715156.json](https://github.com/acmerobotics/road-runner-quickstart/files/13693852/lateral-ramp-1702757715156.json)
<img width="1512" alt="Screenshot 2023-12-16 at 3 21 57 PM" src="https://github.com/acmerobotics/road-runner-quickstart/assets/31151753/05434f36-475e-45d0-a7ef-7501f26f083c">

**Comment by rbrott** [comment]
Lateral ramp logger/regression should only be used with dead wheel localization, not drive encoders. You should do `LateralPushTest` instead.
