### ISSUE TITLE
Documentation Inaccuracy for Extra Correction

### ISSUE THREAD

**Issue by nash-pillai** [acmerobotics/road-runner-quickstart#358]
### RR FTC Version

1.0

### Observed Behavior

![image](https://github.com/acmerobotics/road-runner-quickstart/assets/47931961/0a31605a-0d85-4134-abdf-e2ec3238a231)
https://rr.brott.dev/docs/v1-0/guides/extra-correction/
The +1 is for the current time instead of the time limit. This was cutting off our trajectories and decreasing the accuracy

**Comment by rbrott** [comment]
Oh duh. Fixed now.
