### ISSUE TITLE
Incorrect error calculation by `turnController`

### ISSUE THREAD

**Issue by Calvin-Xu** [acmerobotics/road-runner-quickstart#36]
We have been trying to debug the following issue: [Unexpected heading error behavior](https://github.com/acmerobotics/road-runner-quickstart/issues/35), and have some speculations regarding its cause:

## If we understand correctly...

Since heading error seems to be correct when following a trajectory, we decided that it may be a problem only affecting the drive's in the TURN mode. It appears that in `SampleMecanumDriveBase` the `turnController` used in this mode is separate from the trajectory follower:

```java
private PIDFController turnController;
. . .
follower = new HolonomicPIDVAFollower(TRANSLATIONAL_PID, TRANSLATIONAL_PID, HEADING_PID);
```

Since the heading control in `FOLLOW_TRAJECTORY` seems to work, we are interested in how `headingController` in the follower is different from `turnController` in the drive. They are both `PIDFController`s that have the target position set to zero by default.

```java
/**
* Target position (that is, the controller setpoint).
*/
 var targetPosition: Double = 0.0
```

In the `HolonomicPIDVAFollower`, error seems to be set to the `PIDFController`s by setting setpoint = error (actually right in the comments)

```java
// you can pass the error directly to PIDFController by setting setpoint = error and position = 0
axialController.targetPosition = poseError.x
lateralController.targetPosition = poseError.y
headingController.targetPosition = poseError.heading
```
## What we speculate the error is
But it seems to us that `targetPosition` seems to be never set to and therefore remains 0, and subsequent error calculations seem to be based on it. The debugger output seems to confirm this, as well as the behavior of the heading error (starting at 0, becoming increasingly negative as the counterclockwise turn is executed) we experienced in 
[Issue #35](https://github.com/acmerobotics/road-runner-quickstart/issues/35).

![Imgur](https://i.imgur.com/pCmzDaY.png)

![Imgur](https://imgur.com/NOdDhZV.jpg)

## Proposed fix

We created a pull request that addresses the problem for us: [#37](https://github.com/acmerobotics/road-runner-quickstart/pull/37).

**Comment by rbrott** [comment]
Thanks for identifying the cause. The solution is similar to the PR except the error is updated with the profile at each time step instead of once at the start of the turn.

**Comment by Calvin-Xu** [comment]
Thank you for your support!

**Comment by Calvin-Xu** [comment]
After more careful thinking we realized why our proposed solution is quite wrong and have a better understanding of motion planning & feedforwards. This has been an interesting exercise, and thank you for your support.
