### ISSUE TITLE
"Cannot resolve symbol" in AcmeRobotics

### ISSUE THREAD

**Issue by RyanGOttignon** [acmerobotics/road-runner-quickstart#365]
### RR FTC Version

0.1.12

### Observed Behavior

Upon downloading the newest version of the quickstart and opening it in Android Studio, all `com.acmerobotics.roadrunner` classes fail to resolve.

![image](https://github.com/acmerobotics/road-runner-quickstart/assets/115369841/a47f3d28-f0d9-4cff-87ca-937cb4d04e91)

This is identical to #201, but no answer was given there. It appears in older versions of the quickstart as well (I've tried [`ce080b0b51d7913e58d4682e74b1c63653a74c68`](https://github.com/acmerobotics/road-runner-quickstart/tree/ce080b0b51d7913e58d4682e74b1c63653a74c68) as well, to no avail).

**Comment by rbrott** [comment]
Have you tried building the project or doing a Gradle sync?

**Comment by RyanGOttignon** [comment]
I have tried doing multiple Gradle syncs, and all had this same result. I will try building the project tomorrow, though I suspect it'll just throw the same exception as Android Studio hints at.

**Comment by RyanGOttignon** [comment]
Building works! I'm not sure why the errors appear in Android Studio, but it works while building.

Thank you!

**Comment by niceeffort** [comment]
We had this problem yesterday. The issue was that we could not download the POM files. We solved it by installing [CloudFlare Warp](https://cloudflarewarp.com/) as suggested in this thread: https://www.reddit.com/r/FTC/comments/1at3sb0/is_the_acmerobotics_repo_down_i_cant_download/
