### ISSUE TITLE
Ramsette Controller Error Y not existing

### ISSUE THREAD

**Issue by FalseMSP** [acmerobotics/road-runner-quickstart#370]
### RR FTC Version

0.1.11

### Observed Behavior

Control.kt Ramsete controller is missing a term in the AngVel section. Specifically, it is missing the "error.position.y" term.
Correct expression is
`return PoseVelocity2dDual.constant(
            PoseVelocity2d(
                Vector2d(
                    vRef * error.heading.real + k * error.position.x,
                    0.0
                ),
                omegaRef + k * error.heading.log() + b * vRef * sinc(error.heading.log())*error.position.y,
            ),
            2
        )'

**Comment by rbrott** [comment]
Good catch, should be fixed in the latest core release.
