### ISSUE TITLE
Import Statements in MecanumDrive.java and TankDrive.java having numerous errors

### ISSUE THREAD

**Issue by TheAwesomeKid02** [acmerobotics/road-runner-quickstart#371]
### RR FTC Version

0.1.13

### Observed Behavior

When I open `MecanumDrive.java` and `TankDrive.java`, I can see numerous importing errors. Upon further inspection, I found out that the files don't even exist! The import is like `import com.acmerobotics.roadrunner.Action` (This is an example) but the file does not exist. Same with numerous other classes like `AccelConstraint`, `Arclength`, `VelConstraint`, etc.

**Comment by rbrott** [comment]
Sounds similar to #365. Can you try building the project with the hammer and see if any errors pop up there (click the hammer in the top bar or run `./gradlew build -x lint`)?

**Comment by TheAwesomeKid02** [comment]
Building finished with zero errors. I am connected to regular wifi yet the problem still persists.

**Comment by TheAwesomeKid02** [comment]
![image](https://github.com/acmerobotics/road-runner-quickstart/assets/69116138/6e6b0dda-a69d-4f19-9240-962942dcf8e5)
This is the error of the imports.

**Comment by TheAwesomeKid02** [comment]
Could someone please help me?

**Comment by ftcaarya** [comment]
> Could someone please help me? Or you can recommend someone who can help me.

You could try to clone a new quickstart and transfer all the edits in there this might help

**Comment by TheAwesomeKid02** [comment]
> > Could someone please help me? Or you can recommend someone who can help me.
> 
> You could try to clone a new quickstart and transfer all the edits in there, we had a problem like this and it was resolved by cloning a new quickstart repo.

What edits would I transfer and what new quickstart? I am just asking for further clarification.

**Comment by ftcaarya** [comment]
> > > Could someone please help me? Or you can recommend someone who can help me.
> > 
> > 
> > You could try to clone a new quickstart and transfer all the edits in there, we had a problem like this and it was resolved by cloning a new quickstart repo.
> 
> What edits would I transfer and what new quickstart? I am just asking for further clarification.

All the tuning values that changed and all the opmodes that you created

**Comment by TheAwesomeKid02** [comment]
I have not made any edits on the repo yet. I just opened the files to check them out and I found the errors.

**Comment by ftcaarya** [comment]
> I have not made any edits on the repo yet. I just opened the files to check them out and I found the errors.

Then just clone a new quickstart repo

**Comment by TheAwesomeKid02** [comment]
The problem persists. I tried re-cloning the repo and re-building.

**Comment by vidhuthalla** [comment]
Have you found a solution I am having the same problem

**Comment by vidhuthalla** [comment]
> The problem persists. I tried re-cloning the repo and re-building.


Have you found a solution I am having the same problem

**Comment by TheAwesomeKid02** [comment]
> > The problem persists. I tried re-cloning the repo and re-building.
> 
> 
> 
> 
> 
> Have you found a solution I am having the same problem
> 
> 
> 
> 

Unfortunately, I have not found a solution for this.

**Comment by TullyNYGuy** [comment]
Same issue here. I have a fresh, unmodified download of the quickstart. Invalidating the cache, gradle sync and build (i.e hammer) did not resolve it. The code has "cannot resolve symbol" for all of the com.acmerobotics.roadrunner classes but I have no build errors. That seems odd to me.

**Comment by TullyNYGuy** [comment]
After much messing around, I decided to upgrade gradle from 7.2.0 to 7.3.1. That did not help. Then I upgraded Android Studio from Dolphin to Jellyfish. That fixed the issue.

**Comment by TheAwesomeKid02** [comment]
> After much messing around, I decided to upgrade gradle from 7.2.0 to 7.3.1. That did not help. Then I upgraded Android Studio from Dolphin to Jellyfish. That fixed the issue.

Alright, I will try this. I will let you know if this works.

**Comment by TheAwesomeKid02** [comment]
Good news...
It appears that this error is not present for Android Studio versions after Jellyfish?? (correct me if I am wrong). I upgraded my Android Studio from Dolphin to Koala and it works fine now.
