### ISSUE TITLE
RR goes crazy when going backward with a tank drive and drive encoders

### ISSUE THREAD

**Issue by PythonAtSea** [acmerobotics/road-runner-quickstart#374]
### RR FTC Version

0.1.13

### Observed Behavior

When the robot is doing anything backwards, it goes crazy, not following the path at all. However, when the robot's going forwards, everything's fine. 

https://github.com/acmerobotics/road-runner-quickstart/assets/61562046/6c1dc72f-1d8e-4acc-829a-92429fdf5fa6

https://github.com/acmerobotics/road-runner-quickstart/assets/61562046/92396ccd-f1f1-42b7-9783-e4b5b02853a7

**Comment by rbrott** [comment]
Good catch, should be fixed in https://github.com/acmerobotics/road-runner/commit/5cf5de0712dd16ccccd060508045d71df0573c9b which was released in `v1.0.0-beta8` (https://github.com/acmerobotics/road-runner-quickstart/commit/416ba0d1ad394f6c0b9a60346be5d7a3519e6030).
