### ISSUE TITLE
`SyntaxError: Unexpected end of JSON input` in `ForwardRampLogger`

### ISSUE THREAD

**Issue by Marlstar** [acmerobotics/road-runner-quickstart#391]
### RR FTC Version

1.0.0

### Observed Behavior

When attempting to open the latest logged data for [`ForwardRampLogger`](http://192.168.43.1:8080/tuning/forward-ramp.html), an error occurs due to the raw json file being randomly cut off.
![image](https://github.com/user-attachments/assets/272e458b-b3e6-42b8-9649-3b387c8bd316)
When opening the JSON file, this is evident, as it appears that the file was still being written to before abruptly stopping without completing the JSON formatting.

![image](https://github.com/user-attachments/assets/a6c29e21-df52-4e11-bafb-ea661f327aeb)

### Tuning Files

File: [forward-ramp-1722318233797 (1).json](https://github.com/user-attachments/files/16505245/forward-ramp-1722318233797.1.json)

### Robot Logs

[2024_07_30__15_41_47_398__ForwardRampLogger.log](https://github.com/user-attachments/files/16517613/2024_07_30__15_41_47_398__ForwardRampLogger.log)

**Comment by rbrott** [comment]
As you noticed the file is incomplete. I would just try again, maybe stopping it sooner.

**Comment by Marlstar** [comment]
Hello,
I did actually try running it a few times, including shorter runs, but got the same results. This is strange as I have gone through this tuning stage multiple times before without issue. I will try a few more times just to be sure, but I do not believe it is an issue on my end.

Thanks!

**Comment by Marlstar** [comment]
Hello! Just an update, I am moving back to RR 0.5 for the time being given that it is much more well-known and the community knowledge is much greater. I'll close the issue for now. Thanks :)
