### ISSUE TITLE
Docs: bump versions in the 'install onto an existing project' directions

### ISSUE THREAD

**Issue by Iris-TheRainbow** [acmerobotics/road-runner-quickstart#395]
The versions in the instructions to install Roadrunner onto a pre-existing project are out of date. roadrunner ftc needs to be bumped to 0.1.13 (its on 0.1.12) and dash needs to be bumped to 0.4.16 (it's on 0.4.14).

**Comment by rbrott** [comment]
Should be updated now, thanks!
