### ISSUE TITLE
Inconsistent results from track width tuner

### ISSUE THREAD

**Issue by ethan-robotics** [acmerobotics/road-runner-quickstart#4]
I am getting inaccurate and inconsistent results from the track width tuner. I am using a 4 wheel drive, with traction in the back and omnis in the front. The default settings of the tuner give me a result of 13.09. Using this track width gives me really inaccurate turns. The actual track width of the drivetrain (measured) is 16.5. I tried adjusting the track width manually to provide accurate turns. I got accurate results at  a width of 22.5". I tested multiple combinations of motor power and number of turns (listed below). 

motor power | number of turns | output track width
------------ | ---------------- | ------------------
0.3 | 4 | 13.09
0.3 | 2 | 15.73
0.3 | 6 | 12.2
0.3 | 12 | 11.46
0.5 | 4 | 13.17
0.7 | 4 | 13.36

**Comment by guberti** [comment]
I also experienced this issue. Ultimately, I ended up just tuning the track width myself.

**Comment by guberti** [comment]
I'll give `NewTrackWidthCalibrationOpMode` a go when I tune PID coeffs for our other chassis tomorrow.

**Comment by guberti** [comment]
`TrackWidthCalibrationOpMode ` (the now deprecated one) reliably gave me a track width of ~13.65 in. This  works pretty nicely in testing.

**Comment by guberti** [comment]
But `NewTrackWidthCalibrationOpMode` is giving me ridiculous results. It seems to be doing its job while the robot is running, but it tells me my track width is `-2.45 in` (yes, negative) with a SE of `0.416`.

**Comment by guberti** [comment]
I just realized that I had my track width set to `13.66 in` when running the above op mode. When I instead set track width to 1, it tells me `Effective track width = 42.21 (SE = 43.129)`, which makes just as little sense.

**Comment by rbrott** [comment]
I think most of the issues with `TrackWidthCalibrationOpMode` and `NewTrackWidthCalibrationOpMode` have been fixed. Are there any outstanding problems before I close this? @guberti @ethan-robotics
