### ISSUE TITLE
AngularRampLogger broken due to a problem with 10.0 FTC SDK

### ISSUE THREAD

**Issue by anpark1234** [acmerobotics/road-runner-quickstart#405]
### RR FTC Version

0.1.13

### Observed Behavior

AngularRampLogger is producing weird results with the new 10.0 FTC SDK. With 10.0, the graph doesn't follow a straight line, the angular velocity is really high, and the resulting track width calculated is way too low. I've attached the plots from the same code and robot using SDK 9.2 vs. 10.0.

It appears there is a problem with imu.getRobotAngularVelocity(AngleUnit.RADIANS) returning strange values. See [the issue filed here](https://github.com/FIRST-Tech-Challenge/FtcRobotController/issues/1070).

I downloaded the road-runner-ftc project so I could modify AngularRampLogger in Tuning.kt, and I implemented a workaround in my local version which appears to resolve the problem:

```
val av = view.imu.get().getRobotAngularVelocity(AngleUnit.**DEGREES**)
val time = t.addSplit()

data.angVels[0].times.add(time)
data.angVels[1].times.add(time)
data.angVels[2].times.add(time)

data.angVels[0].values.add(**Math.toRadians(**av.xRotationRate.toDouble()**)**)
data.angVels[1].values.add(**Math.toRadians(**av.yRotationRate.toDouble()**)**)
data.angVels[2].values.add(**Math.toRadians(**av.zRotationRate.toDouble()**)**)
```

Do we need to wait for a fix in the SDK or can you check and implement this workaround in RR?

![TrackWidthRegression_v9_2](https://github.com/user-attachments/assets/9c0d70a4-9058-4437-8f84-daf0fd047946)
![TrackWidthRegression_v10_0](https://github.com/user-attachments/assets/2363462d-9b51-4ef0-b082-30ab53cd1718)

**Comment by ArushYadlapati** [comment]
I am also having this issue with 3 Dead Wheel Odometry. In the near future when I try tuning RR v.1.0 with OTOS, I will see if this also happens with `AngularRampLogger`, as you only need `trackWidthTicks`.
