### ISSUE TITLE
Difference between followtrajectory and followtrajectory sync

### ISSUE THREAD

**Issue by AsianKoala** [acmerobotics/road-runner-quickstart#41]
What is the difference between followTrajectory and and followTrajectorySync? And was turnTo and turn in TrajectoryBuilder changed to turnSync/turn under the SampleMecanumDriveBase class?

**Comment by rbrott** [comment]
`followTrajectory()` starts following a trajectory. The user is then responsible for calling `update()` in a loop to actually set motor powers until the trajectory is finished. `followTrajectorySync()` does all of this for you at the cost of blocking until the trajectory is completed.

Yes, `turnTo()` and `turn()` have been removed from `TrajectoryBuilder`. Trajectories in 0.4.+ are now only composed of time-parametrized paths (no more turns, waits, etc.). To fill this gap in Road Runner's core functionality, the quickstart has `turn()`/`turnSync()` which show how to implement point turns directly using 1D motion profiles.
