### ISSUE TITLE
I'm getting an error for my AutoMode that nobody can figure out. I have done a lot so please help "One or more of the attached Lynx Modules has outdated firmware (It is all up to date and on the suggested 1.8.2 version)." "Expansion Hub 2: (unparseable) null" Control Hub: (unparseable null)

### ISSUE THREAD

**Issue by Leoshrotri** [acmerobotics/road-runner-quickstart#425]
### RR FTC Version

0.1.14

### Observed Behavior

I have no idea why this is popping up because I already have my control hub, expansion hub, and driver hub all up to date on the 1.8.2 version that it is suggesting. I tried REV Hardware Client or whatever its called and everything is up to date. I have no idea why no code will even run and why the error only shows up after I click stop. I have also tried to re-install the firmware on the hubs and check the wiring between everything and they are all fine. The issue still persists. Please help me figure this out. FTC discord says this is a first of a kind issue nobody can seem to figure out. I don't know why it says null if everything is there please help, this is my last option I have literally done everything.
<img width="435" alt="Screenshot 2024-10-23 at 9 55 32 PM" src="https://github.com/user-attachments/assets/aca52d56-32f2-48ef-b0d9-75fb5ee6fff9">
<img width="935" alt="Screenshot 2024-10-23 at 9 55 25 PM" src="https://github.com/user-attachments/assets/dd375376-6375-42a7-9f51-234ee291b7d8">
<img width="896" alt="Screenshot 2024-10-23 at 9 55 15 PM" src="https://github.com/user-attachments/assets/ad345002-6df3-403f-9e9a-6f668990c5d2">
<img width="1451" alt="Screenshot 2024-10-23 at 9 55 03 PM" src="https://github.com/user-attachments/assets/d409f9e9-55eb-46ed-8725-2e878f9a73ad">
<img width="603" alt="Screenshot 2024-10-23 at 5 49 08 PM" src="https://github.com/user-attachments/assets/b8191d99-2c92-4e55-8dc0-18ead767fd33">

**Comment by rbrott** [comment]
You can remove this line to get it to stop crashing: https://github.com/acmerobotics/road-runner-quickstart/blob/8e7870ff1e9dfe3547b2aae60dfded00e736bc69/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MecanumDrive.java#L212.

Not sure why the version is garbage though. You may have a more serious issue with the connection to the hubs or something.

**Comment by Leoshrotri** [comment]
Is there anything wrong in my auto mode coding?

**Comment by Leoshrotri** [comment]
Because the error only pops up after I press stop. nothing happens when i click start, there are no actions taking place from the coding and there is no error that shows up until I press stop. I don't know why this is or if this is irregular behavior, is the code wrong?
