### ISSUE TITLE
[Q] Admissible error & timeout with followers

### ISSUE THREAD

**Issue by Calvin-Xu** [acmerobotics/road-runner-quickstart#45]
During testing we discover one issue: the follower often finishes following a trajectory with quite some positional error in the end. In the dashboard we can see that error is being still reduced by the PID controllers when the following stopped.

Looking at `HolonomicPIDVAFollower` and `TrajectoryFollower`, we think that `admissibleError` and `timeout` should be set to address this issue. Since they are by default zero, we wonder if there might be other considerations that we are overlooking. Advice on best practices will be great!

**Comment by rbrott** [comment]
Ideally, you should try to characterize the error (if it's systematic). For instance, maybe the robot strafes more slowly and you can measure that empirically and hopefully correct for it. If the error is not systematic, you can still correct for it with feedback/follower PID.

If you still can't achieve the desired error tolerance with those methods, you can try messing with `admissibleError` and `timeout`. The `admissibleError` pose is simply the per-robot-DOF satisfactory error, and `timeout` is the duration you're willing for the robot to achieve that goal.
