### ISSUE TITLE
Do I need the IMU for a 3 Dead Wheel Config?

### ISSUE THREAD

**Issue by GreenEggsAndProgram** [acmerobotics/road-runner-quickstart#459]
Do I need the IMU for a 3 Dead Wheel Config? I'm wondering because in the last version of Road Runner you didn't. But now, when I run AngularRampLogger, it says it isn't getting any IMU feedback and the graphs all have vertical slopes.

**Comment by rbrott** [comment]
You only need an IMU to tune the positions of the three dead wheels. I highly recommend this steps, though you can set your offsets manually based on measurements if you want to skip that step.

**Comment by GreenEggsAndProgram** [comment]
Ok, thanks for all the help and responding so quick!
