### ISSUE TITLE
No 1-D Motion Sample

### ISSUE THREAD

**Issue by guberti** [acmerobotics/road-runner-quickstart#5]
Shouldn't be too difficult to add. Would also be nice to know how controlling linear movement (i.e. moving up a lift) is different PID-wise than rotary movement (i.e. rotating an arm).

**Comment by rbrott** [comment]
Check out the new elevator samples. Rotary motion is pretty much the same (I may add a sample).

**Comment by guberti** [comment]
New updates are really nifty. Arm is working nicely now. Thanks!
