### ISSUE TITLE
How to Setup dead wheel tracking

### ISSUE THREAD

**Issue by JFullerFPV** [acmerobotics/road-runner-quickstart#52]
I'm currently trying to implement three-wheel tracking into the quickstart but I don't exactly know what to do. In SampleMechanumDriveREV it says `  // TODO: if desired, use setLocalizer() to change the localization method` How do I go about doing this? I've tried putting this line of code  `setLocalizer(StandardTrackingWheelLocalizer);` there but it doesn't seem to be working. What do I need to do?

**Comment by rbrott** [comment]
`setLocalizer(new StandardTrackingWheelLocalizer(hardwareMap))`
