### ISSUE TITLE
Outdated Lynx Firmware

### ISSUE THREAD

**Issue by CookedPelvis** [acmerobotics/road-runner-quickstart#53]
Hi there,

When attempting to run the LocalizationTest.java in the quickstart project, the code threw the `LynxFirmwareVersionException` error. It says that our attached lynx modules have outdated firmware, and that the minimum version was 1.8.2. 

How can we update this firmware?

**Comment by rbrott** [comment]
http://www.revrobotics.com/software/#ExpansionHubFirmware
