### ISSUE TITLE
lag upon initialization

### ISSUE THREAD

**Issue by LetianLi** [acmerobotics/road-runner-quickstart#56]
Our phones have 2+ seconds of initialization normally and when the imu problem message pops up, 5+ seconds. This is a big problem for competition and the switch from auto to teleop.

**Comment by rbrott** [comment]
This doesn't seem like a Road Runner issue. Perhaps you should file an issue [here](https://github.com/FIRST-Tech-Challenge/SkyStone).

**Comment by LetianLi** [comment]
the lag happens when initializing with road runner. That seems to be the main problem.

**Comment by rbrott** [comment]
If you don't use the IMU, there's no need to initialize it. In this respect, the quickstart code is just like a normal op mode.

**Comment by LetianLi** [comment]
Even without the imu, it takes a while.

**Comment by LetianLi** [comment]
would calling the road runner libraries cause lag?

**Comment by rbrott** [comment]
Probably not, but it's possible with misuse (e.g., arc length parametrization of a spline with high curvature). You should profile and find out for yourself.
