### ISSUE TITLE
CONTROL HUB PROBLEM

### ISSUE THREAD

**Issue by ana-andreea** [acmerobotics/road-runner-quickstart#58]
I m not able to update the on-bot-java to Java 8 and I can't build the program that contains "lambda". Is there any way i can update the pre-installed program to make it work? Is there anyone who is able to use Road-Runner and the DashBoard with the REV Control Hub?

**Comment by rbrott** [comment]
Neither Road Runner nor FTC Dashboard support OnBotJava or Blocks. These libraries work perfectly fine with Control Hubs; however, you must use Android Studio.

Also, in the future, you only need to open a single issue. I can always transfer it to a different repo if it fits better.
