### ISSUE TITLE
FTC Dashboard

### ISSUE THREAD

**Issue by mihir-jain** [acmerobotics/road-runner-quickstart#59]
When I try to run FTC Dashboard, the side of the screen, starts to blank out, and the most common "mode" is saying that it isn't active

**Comment by rbrott** [comment]
You'll have to elaborate. Do you have a screenshot? What does the blue text on the RC phone read?

**Comment by mihir-jain** [comment]
This is what happens what I run it: https://photos.app.goo.gl/Ntyfbo3uG1PCCNvb7
The blue text on the RC says: "Dashboard: server attached, no connections"

**Comment by rbrott** [comment]
Is anything blocking the websocket? I would check the devtools network tab.

**Comment by mihir-jain** [comment]
what do you mean?

**Comment by rbrott** [comment]
https://developer.mozilla.org/en-US/docs/Glossary/Developer_Tools

**Comment by mihir-jain** [comment]
I dont think so, because FTC Dashboard has worked before, just on skystone master, not on RR

**Comment by mihir-jain** [comment]
And how do I check the devtools network tab?

**Comment by mihir-jain** [comment]
![image](https://user-images.githubusercontent.com/48145592/74110937-7c645c00-4b45-11ea-8f5c-d53406f356f9.png)
It is doing this every few seconds, creating a new one
