### ISSUE TITLE
Increasing power

### ISSUE THREAD

**Issue by Mihneaghitu** [acmerobotics/road-runner-quickstart#63]
Is there any way to increase motor power for all type of movements while still keeping PID coefficients intact? We have succesfully made several autonomous with all kind of movements(spline, strafe etc.), however we would want the robot to move faster as it has a big mass and moves quite slow.

**Comment by rbrott** [comment]
Yes, the constraints apply to all movements. There's no guarantee that the same PID coefficients will work, but that's mainly a question of the relative nonlinearity of the system.

**Comment by Mihneaghitu** [comment]
Great! We will increase the constraint values and recalibrate the PID coefficients. Thanks a lot!
