### ISSUE TITLE
Accessing hardware parts în autonomous

### ISSUE THREAD

**Issue by Mihneaghitu** [acmerobotics/road-runner-quickstart#68]
Hello,
     We were building the autonomous while we encountered a problem: we cannot action every motor independently from our 'robot' object of the SampleMecanumRevOptimized class. For e ample, when we type ' robot. ' there seems to appear only the servo object we created in the hardware class. Could you provide a way to give power to the motor?
Thanks a lot!

**Comment by rbrott** [comment]
If you want to access the motor instance variables externally, you can change their visibility to `public`.

**Comment by Mihneaghitu** [comment]
Thanks a lot! Also, I am trying to load a file from `FtcRobotController/assets` to the method in the autonomous `TrajectoryLoader.load()`. How should the parameter in the method look like? My file is called trajectory_test.yaml.

**Comment by rbrott** [comment]
"trajectory_test"

You should move the file into a `trajectory` folder within the assets folder.

**Comment by Mihneaghitu** [comment]
I did both and it gives me an error: 
`Trajectory traj1 = TrajectoryLoader.load("trajectory_test");`
`load(java.io.file) in TrajectoryLoader cannot be applied to (java.lang.String).`

**Comment by rbrott** [comment]
No, you should use `AssetsTrajectoryLoader`.
