### ISSUE TITLE
StraightTest at the end robot is rolling an inch or two back

### ISSUE THREAD

**Issue by jeevan-navudu** [acmerobotics/road-runner-quickstart#73]
The graph below is the graph done for a robot with high rpm motors using encoders. Tuned the DriveVelocityPidTuners and then did a StraightLine test. To minimize the error adjusted the kV and kA. How do I eliminate the rollback I am seeing at the end of the test. I am seeing the same rollbacks during the auton mode.

![image](https://user-images.githubusercontent.com/56749501/76066766-1223b900-5f43-11ea-848d-3dff15c2327c.png)

**Comment by rbrott** [comment]
If you don't have feedback, this is probably a symptom of a large kA. It may be that acceleration and deceleration are not exactly symmetric. In this case, position feedback is probably enough to pick up the slack.
