### ISSUE TITLE
Help with StandardTrackingWheelLocalizer

### ISSUE THREAD

**Issue by AndreiSpiru** [acmerobotics/road-runner-quickstart#75]
Hello! Me and my team have recently tried implementing a dead wheel system and have had a lot of trouble using it. We read up all there is on the internet but nothing seems to help. The encoders seem fine, the values change in the right direction but at a completely wrong pace in the localizer test. For example, a 360-degree turn is more like 200 degrees in reality and distances traveled are not right. We have measured all constants and it all seems fine, but there still are these issues. Any help would be greatly appreciated!

**Comment by rbrott** [comment]
> The encoders seem fine, the values change in the right direction but at a completely wrong pace in the localizer test. For example, a 360-degree turn is more like 200 degrees in reality and distances traveled are not right.

Sounds like you should try adjusting the distance between the left/right wheels (if you're using a standard setup).
