### ISSUE TITLE
NewTrackWidthCalibrationOpMode gives negative value for track width

### ISSUE THREAD

**Issue by guberti** [acmerobotics/road-runner-quickstart#8]
I'm no expert, but distances generally tend to be positive. Maybe this has to do with the robot rotating the "wrong" direction? The old track width calibration op mode gives me a positive value, as expected.
![image](https://user-images.githubusercontent.com/3069006/48235270-20bf8780-e372-11e8-928b-f44fceaad1aa.png)

**Comment by rbrott** [comment]
The signs should be correct provided that the robot coordinate frame agrees with Road Runner's conventions. That is, positive X is taken to be forward (from the perspective of the robot), positive Y is taken to be left, and positive Z rotation is taken to be counterclockwise. If you believe your robot adheres to these conventions, please attach your implementation of `getExternalHeading()`.
